### ISSUE TITLE
Error when building helloworld example

### ISSUE THREAD

**Issue by arturboronat** [mdenet/educationplatform-tooltemplate#2]
I'm getting [this error](https://gist.github.com/arturboronat/77dfc1a864d515059c1ad537cc649190) when trying to compile the hello world example with `mvn clean install -Phelloworld`.

After importing the projects into Eclipse, I'm also getting the following errors:
![Screenshot 2023-06-29 145451](https://github.com/mdenet/educationplatform-tooltemplate/assets/14847623/e2e79985-5a73-4f7e-a041-0dec8327cc40)

**Comment by szschaler** [comment]
@barnettwilliam this is perhaps something that would be useful to run as a GitHub Action in this repository?

**Comment by barnettwilliam** [comment]
Afternoon Artur, it looks like it's can't find `com.mde-network.ep.toolfunctions.emf`. 

Have you also compiled the [core dependencies](https://github.com/mdenet/educationplatform-tooltemplate#build-core-dependencies) so that they are availablie in your local maven repository? The core dependencies are in the services of the (tool-functions)[https://github.com/mdenet/platformtools]  git repository. 

I can add a GitHub action to check the build steps.

**Comment by arturboronat** [comment]
Thanks, both. I had not cloned platformtools. I should have paid more attention but a hyperlink could be added in the documentation to highlight that this is a separate repository.

Nonetheless, after cloning the repo, and execute `mvn clean install -Pall`, I'm getting the error below:

```
PS C:\Users\ab373\Documents\git-mde-education> git clone https://github.com/mdenet/platformtools.git
Cloning into 'platformtools'...
remote: Enumerating objects: 810, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (59/59), done.
Receiving objects: 100% (810/810), 300.34 KiB | 4.42 MiB/s, done.

Resolving deltas: 100% (299/299), done.
PS C:\Users\ab373\Documents\git-mde-education> cd .\platformtools\
PS C:\Users\ab373\Documents\git-mde-education\platformtools> mvn clean install -Pall
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.066 s
[INFO] Finished at: 2023-06-29T17:20:36+01:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "all" could not be activated because it does not exist.
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\ab373\Documents\git-mde-education\platformtools). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
```

**Comment by arturboronat** [comment]
Ups, missed `cd ./services`, working through it now.

**Comment by arturboronat** [comment]
It built well (after a good half an hour). However, the project helloworld is still missing a bundle dependency:
![Screenshot 2023-06-29 213956](https://github.com/mdenet/educationplatform-tooltemplate/assets/14847623/9d3e4929-f365-4540-943d-222080b1bc0f)

**Comment by barnettwilliam** [comment]
Yes the first time building takes a while, it should be much quicker subsequently. 

Is the eclipse target platform set to the target file that's in the project com.mde-network.ep.toolfunction.helloworld?

So under Window > Preferences and then in preferences panel dialog box that appears and under Plug-in Development > Target Platform in the left hand panel, make sure the mdenettoo-helloworld target file is active (shown in the screenshot).

If it isn't select and apply it. I've also found that I have to restart eclipse after changing target files for it to be picked up.

![preferences_target](https://github.com/mdenet/educationplatform-tooltemplate/assets/32113205/927eb781-3908-4c6c-bd92-7debdf0f21c5)

**Comment by szschaler** [comment]
@barnettwilliam is it worth adding that step to the documentation if it's not there already?

**Comment by barnettwilliam** [comment]
> @barnettwilliam is it worth adding that step to the documentation if it's not there already?

Agreed, I've updated the readme to include some eclipse setup details, some mandatory maven plugins Artur and I came across today that are required, and added a link to platformtools.
